rootProject.name = "java-gyak"

include("1")
include("1:1")
include("1:2")
include("1:3")
include("1:4")
include("1:5")
include("1:6")
include("1:7")

include("2")
include("2:Fel1")
include("2:Fel2")
include("2:Fel3")
include("2:Fel4")
include("2:Fel5")

include("3")
include("3:1")
include("3:2")
include("3:3")
include("3:4")
include("3:6")
include("3:7")
include("3:7.1")

//include("4:ropi")
include("4:4")
//include("4:5.0")
include("4:5")

include("5")
include("5:1")
include("5:4")

include("5-sol")
include("5-sol:fel1")
include("5-sol:fel2")
include("5-sol:fel3")
include("5-sol:fel4")
include("5-sol:fel5")
include("5-sol:extra:fel1")
include("5-sol:extra:fel2")
include("5-sol:extra:fel3")

include("6:0")
include("6:1")

include("6-sol")
include("6-sol:fel1")
include("6-sol:fel1:a")
include("6-sol:fel1:b")
include("6-sol:fel2")
include("6-sol:fel3")
include("6-sol:extra:fel1")

include("7-sol:fel1")
include("7-sol:fel2")
include("7-sol:fel3")

include("8-sol")
include("8-sol:extra")
include("8-sol:extra:fel1")
include("8-sol:extra:fel2")
include("8-sol:bitwiseexample")
include("8-sol:datastructures")
include("8-sol:datastructures_original_KTO")
include("8-sol:immutableStrArr")

include("9-sol")
include("9-sol:example")
include("9-sol:fel1")
include("9-sol:fel2")
include("9-sol:fel4-a")
include("9-sol:fel4-b")
include("9-sol:fel4-c")
